# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{nokogiri-happymapper}
  s.version = "0.3.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Damien Le Berrigaud", "John Nunemaker", "David Bolton", "Roland Swingler", "Etienne Vallette d'Osia"]
  s.date = %q{2010-12-23}
  s.description = %q{Object to XML Mapping Library, using Nokogiri (fork from John Nunemaker's Happymapper)}
  s.email = %q{damien@meliondesign.com}
  s.extra_rdoc_files = [
    "README.md",
    "TODO"
  ]
  s.files = [
    "lib/happymapper.rb",
    "lib/happymapper/attribute.rb",
    "lib/happymapper/element.rb",
    "lib/happymapper/item.rb",
    "lib/happymapper/text_node.rb"
  ]
  s.homepage = %q{http://github.com/dam5s/happymapper}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Provides a simple way to map XML to Ruby Objects}
  s.test_files = [
    "spec/fixtures/address.xml",
    "spec/fixtures/ambigous_items.xml",
    "spec/fixtures/analytics.xml",
    "spec/fixtures/analytics_profile.xml",
    "spec/fixtures/commit.xml",
    "spec/fixtures/current_weather.xml",
    "spec/fixtures/dictionary.xml",
    "spec/fixtures/family_tree.xml",
    "spec/fixtures/lastfm.xml",
    "spec/fixtures/multiple_namespaces.xml",
    "spec/fixtures/multiple_primitives.xml",
    "spec/fixtures/pita.xml",
    "spec/fixtures/posts.xml",
    "spec/fixtures/product_default_namespace.xml",
    "spec/fixtures/product_no_namespace.xml",
    "spec/fixtures/product_single_namespace.xml",
    "spec/fixtures/quarters.xml",
    "spec/fixtures/radar.xml",
    "spec/fixtures/statuses.xml",
    "spec/happymapper_attribute_spec.rb",
    "spec/happymapper_element_spec.rb",
    "spec/happymapper_item_spec.rb",
    "spec/happymapper_spec.rb",
    "spec/happymapper_text_node_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, ["~> 1.4.2"])
      s.add_development_dependency(%q<rspec>, ["~> 1.3.0"])
    else
      s.add_dependency(%q<nokogiri>, ["~> 1.4.2"])
      s.add_dependency(%q<rspec>, ["~> 1.3.0"])
    end
  else
    s.add_dependency(%q<nokogiri>, ["~> 1.4.2"])
    s.add_dependency(%q<rspec>, ["~> 1.3.0"])
  end
end

